name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm i -g @railway/cli@latest

      - name: Validate Railway secrets present
        shell: bash
        run: |
          if [ -z "$RAILWAY_TOKEN" ]; then echo "RAILWAY_TOKEN missing"; exit 1; fi
          if [ -z "$RAILWAY_PROJECT_ID" ]; then echo "RAILWAY_PROJECT_ID missing"; exit 1; fi

      - name: Authenticate to Railway (token)
        shell: bash
        run: |
          railway logout || true
          railway login --token "$RAILWAY_TOKEN"
          railway whoami

      - name: Link Railway project
        run: |
          railway link -p "$RAILWAY_PROJECT_ID"

      - name: Show current Railway variables
        run: |
          echo "=== Current Railway Variables ==="
          railway variables || echo "Failed to get variables"
          
      - name: Configure environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
        run: |
          echo "=== Setting Railway Variables ==="
          
          # Always set RESEND_API_KEY 
          railway variables set RESEND_API_KEY="re_W2uvh1cK_9DDTC1AShSxqEQGMPeo75N2o"
          
          # Set SESSION_SECRET if provided, otherwise use default
          if [ -n "$SESSION_SECRET" ]; then
            railway variables set SESSION_SECRET="$SESSION_SECRET"
          else
            railway variables set SESSION_SECRET="calmkaaj-super-secret-session-key-production-2025-$(date +%s)"
          fi
          
          # Set DATABASE_URL if provided
          if [ -n "$DATABASE_URL" ]; then
            railway variables set DATABASE_URL="$DATABASE_URL"
            echo "✅ DATABASE_URL set from secret"
          else
            echo "❌ DATABASE_URL not provided in GitHub secrets"
            echo "🔍 Checking if Railway Postgres service exists..."
            # Try to get DATABASE_URL from Railway Postgres service
            railway variables --service postgres || echo "No postgres service found"
          fi
          
          # Set optional VAPID keys
          [ -n "$VAPID_PUBLIC_KEY" ] && railway variables set VAPID_PUBLIC_KEY="$VAPID_PUBLIC_KEY" || echo "VAPID_PUBLIC_KEY not set"
          [ -n "$VAPID_PRIVATE_KEY" ] && railway variables set VAPID_PRIVATE_KEY="$VAPID_PRIVATE_KEY" || echo "VAPID_PRIVATE_KEY not set"
          
          echo "=== Final Railway Variables ==="
          railway variables

      - name: Deploy using pre-built Docker image
        run: |
          echo "🚀 Deploying pre-built Docker image..."
          # Use the latest built image from GHCR
          railway service --image ghcr.io/ssameershahid/co-working-space:latest
          echo "✅ Deployment complete!"


